# -*- coding: utf-8 -*-
"""CGPA_cal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10T5QUI611oWrNNsg4pt3J-Us29Jk8o2Z
"""

input1 = int(input("How many courses you completed?(before this semester) - "))
input2 = float(input("Current CCGPA(before this semester) - "))
input3 = int(input("How many courses take this semester? - "))
sum1 = 0
for i in range(input3):
    input4 = float(input(f"Course{i+1} CGPA - "))
    sum1 += input4
result = ((input2 * input1) + (sum1))/(input1+input3)
print(f"CGPA: {round(result, 2)}")